### ISSUE TITLE
Missing a DTMFType

### ISSUE THREAD

**Issue by Crayder** [relative/node-bria#2]
https://github.com/relative/node-bria/blob/4d3425d711c5fb270ee42ea4f821c383632de9d4/src/client/Call.ts#L67

"pulse" is also a DTMF type support by Bria API. This sends the DTMF and stops it in one go.

... I know what you're thinking though, the API's documentation says nothing about this and lots of other things. Even the old PDF docs only mention start and stop. I found 'pulse' in their examples on the Counterpath Github. You might glance through those and see if you're missing anything else, this was just something I noticed because I'm also writing a wrapper for AHK.

**Comment by Crayder** [comment]
https://github.com/CounterPath/Bria_API_CSharp_SampleApp_3/blob/93aeada997411b1d7e5fc5531886ddf6f763e57c/Bria_API_SampleApp_Phone/BriaAPIWrapper.cs#L1152-L1157

**Comment by relative** [comment]
Thanks, the Bria docs are atrocious. I have pending emails to counterpath that haven't received a reply in months.

**Comment by Crayder** [comment]
If you go to the website > Support > Submit a Ticket, they usually respond pretty quickly there. Pretty sure all of my responses have been same or next day.
